server:
    port: 8300

spring:
    datasource:
        url:jdbc:h2:file:~/refdatadb
        username:root
    jpa:
        properties:
            hibernate:
                dialect:org.hibernate.dialect.H2Dialect
                ddl-auto:update

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7900/eureka
logging:
    level:
        org:
            springframework:
                security: DEBUG