server:
    port: 8200
spring:
    rabbitmq:
        host:localhost
        port:5672
        username:guest
        password:guest
spring:
    datasource:
        url:jdbc:h2:file:~/tradesdb
        username:root
spring:
    jpa:
        properties:
            hibernate:
                dialect:org.hibernate.dialect.H2Dialect
            hibernate:
                ddl-auto:update

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7900/eureka
logging:
    level:
        org:
            springframework:
                security: DEBUG